version: 0.2

env:
  variables:
    PYTHON_VERSION: python3.11

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli jq

  pre_build:
    commands:
      - echo "Installing dependencies into Lambda Layer..."
      - mkdir -p layer/python/lib/${PYTHON_VERSION}/site-packages
      - pip install -r requirements.txt -t layer/python/lib/${PYTHON_VERSION}/site-packages

  build:
    commands:
      - sam build

  post_build:
    commands:
      - echo "Deploying SAM application (Lambda Layer)..."
      - sam deploy \
          --stack-name lambda-layer-only \
          --region $AWS_DEFAULT_REGION \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --resolve-s3
          --no-interactive

      - echo "Fetching new Lambda Layer ARN from CloudFormation export..."
      - LAYER_ARN=$(aws cloudformation list-exports \
          --query "Exports[?Name=='LayerVersionArn'].Value" \
          --output text)

      - echo "LAYER_ARN=$LAYER_ARN"

      - echo "Fetching existing layers for $FUNCTION_NAME..."
      - EXISTING_LAYERS=$(aws lambda get-function-configuration \
          --function-name $FUNCTION_NAME \
          --query 'Layers[*].Arn' \
          --output text)

      - echo "Updating Lambda function with new layer..."
      - aws lambda update-function-configuration \
          --function-name $FUNCTION_NAME \
          --layers $LAYER_ARN $EXISTING_LAYERS
