version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - mkdir -p layer/python
      - pip install -r requirements.txt -t layer/python

  build:
    commands:
      - echo "Running SAM build..."
      - sam build

  post_build:
    commands:
      - echo "Deploying with SAM..."
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name lambdalayer-test --capabilities CAPABILITY_IAM --region us-east-2
