version: 0.2

env:
  variables:
    PYTHON_VERSION: python3.11

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "Installing dependencies into Lambda Layer..."
      - mkdir -p layer/python/lib/${PYTHON_VERSION}/site-packages
      - pip install -r requirements.txt -t layer/python/lib/${PYTHON_VERSION}/site-packages

  build:
    commands:
      - echo "Running sam build..."
      - sam build

  post_build:
    commands:
      - echo "Deploying Lambda Layer with sam deploy..."
      - sam deploy \
          --stack-name lambda-layer-only \
          --region $AWS_DEFAULT_REGION \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --resolve-s3
